<?php
 // module/Album/view/album/album/delete.phtml:

 $title = $this->translate('Edit Album');
 $this->headTitle($title);
 ?>
<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
 

 <?php 
 $form->prepare();
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 //$form->prepare();

 echo $this->form()->openTag($form);
 foreach ($form as $element) {
 	echo '<div class = "form-group">';

 	echo '<label for="'.$element->getAttribute('name').'">'.$this->translate($element->getLabel()).'</label>';
 	echo $this->formElement($element);
 	echo $this->formElementErrors($element);

        if(strpos($this->formElement($element), "submit") ){
            echo '<a class = "btn-cancel btn btn-primary " href="' . $this->url('album',array('action'=>'index')) . '">' . $this->translate('Cancel') . '</a>';
        }
        echo '</div>';
 }
 echo $this->form()->closeTag();
 ?>