<?php
 
 $title = 'My albums';
 $this->headTitle($title);
?>
 
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <div class="container">
                <h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>     
                <span class="btn btn-default">
                    <strong>
                        <a href="<?php echo $this->url('album', array('action'=>'add'));?>"> <?php echo $this->translate('Add new album') ?></a>
                    </strong>

                </span>

            </div>
        </div>
        
    </div>
</div>
 <table class="table">
            
                  <div id="menu-container">
                    <div id="menu-1" class="homepage">
                        <div class="row">     
            <?php foreach ($albums as $album) : ?>
                            <div class="col-md-4 col-sm-6 col-xs-12 portifolio">
                                <div class="row">
                                    <a id="btn_edit" class="btn btn-primary" href="<?php echo $this->url('album',
                                                array('action'=>'edit', 'id' => $album->id));?>"> <?php echo $this->translate('Edit');?> </a>

                                    <a id="btn_del" class="btn btn-danger" href="<?php echo $this->url('album',
                                                array('action'=>'delete', 'id' => $album->id));?>"> <?php echo $this->translate('Delete');?> </a>

                                    <a id="btn_list" class="btn btn-warning" href="<?php echo $this->url('album',
                                                array('action'=>'addMusica', 'id' => $album->id));?>"> <?php echo $this->translate('List');?> </a>
                                </div>    
                                <div class=" row portfolio-item">
                                    <?php echo 'Musica: ',$this->escapeHtml($album->title);?>
                                    <?php echo 'Artista: ',$this->escapeHtml($album->artist);?>
                                    
                                    <a class="fancybox" href="<?php echo $album->file;?>">
                                            <img src="<?php echo $album->file;?>" >
                                    </a>
                                </div> 
                            
                </div>
                       
            <?php endforeach; ?>
                             </div> 
                    </div> 
                </div>
            
                    
 </table>
