<?php echo $this->doctype(); ?>

<html lang="pt-Br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/fancybox/source/jquery.fancybox.css?v=2.1.5') 
                        ->prependStylesheet($this->basePath() . '/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5') 
                        ->prependStylesheet($this->basePath() . '/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/fancybox/lib/jquery.mousewheel-3.0.6.pack.js',   'text/javascript')
            ->prependFile($this->basePath() . '/fancybox/source/jquery.fancybox.pack.js?v=2.1.5',   'text/javascript')
            ->prependFile($this->basePath() . '/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5',   'text/javascript')
            ->prependFile($this->basePath() . '/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6',   'text/javascript')
            ->prependFile($this->basePath() . '/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7',   'text/javascript')
            ->prependFile($this->basePath() . '/js/fancybox-effects.js','text/javascript')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.file-input.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js');
        






         ?>
        <script>
            $(document).ready(function() {
                    $(".fancybox").fancybox({
                            openEffect	: 'none',
                            closeEffect	: 'none'
                    });
            });
            </script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    
                    <div class="collapse navbar-collapse">
                        <?php
                        echo $this->navigation('navigation')
                                      ->menu()
                                      ->setMinDepth(0)
                                      ->setMaxDepth(0)
                                      ->setUlClass('nav navbar-nav');
                        ?>
                    </div>
                    
                    <!--<ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>-->
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p> Desenvolvido usando Zend por JSCodeGroup</p>
            </footer>
        </div> <!-- /container -->
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
